name: CD

on:
  workflow_call:

jobs:
  cd-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel Deploy for Main Branch
        run: curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}

  cd-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel Deploy for Staging Branch
        run: curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK_STAGING }}
