name: CI + CD

on:
  push:
  pull_request:

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  cd:
    needs: ci
    if: github.event_name == 'push'
    uses: ./.github/workflows/cd.yml
    secrets: inherit
